# Generated by Django 2.1 on 2018-09-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zj_presonal_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('details', models.TextField(max_length=400)),
                ('image', models.ImageField(default='', max_length=50, upload_to='')),
                ('files', models.FileField(default='', max_length=50, upload_to='')),
                ('date', models.DateField(default='')),
                ('bounty', models.IntegerField(default='')),
                ('demand_tel', models.CharField(max_length=13)),
                ('address', models.CharField(default='', max_length=50)),
                ('add_service', models.IntegerField(default='')),
                ('taocan', models.CharField(default='无套餐', max_length=20)),
                ('onclick', models.IntegerField(default=0)),
                ('review', models.IntegerField(default=2)),
                ('personal_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zj_presonal_center.Personal_Center')),
            ],
            options={
                'db_table': 'demand',
            },
        ),
        migrations.CreateModel(
            name='First_Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'first_display',
            },
        ),
        migrations.CreateModel(
            name='Second_Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('first_display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zj_release_demand.First_Display')),
            ],
            options={
                'db_table': 'second_display',
            },
        ),
        migrations.AddField(
            model_name='demand',
            name='second_display',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zj_release_demand.Second_Display'),
        ),
    ]
